spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hr
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    database: mysql

    static-path-pattern: /image\
    resources:
      static-locations: file:E:\何北清\第三阶段项目\Hotel_Management\Hotel Management\src\main\resources\static\images\

